### ISSUE TITLE
Module `tensorflow` has no attribute 'Session' when instantiating a Problem

### ISSUE THREAD

**Issue by ninamiolane** [pymanopt/pymanopt#111]
When trying to use `pymanopt` with the Hypersphere geometry of `geomstats` in numpy, I run into this tensorflow error. Any idea where it might come from? Thank you! 

File: https://github.com/geomstats/geomstats/blob/master/examples/geomstats_in_pymanopt.py
Python: 3.7.7

>> python3 examples/geomstats_in_pymanopt.py
```                                                                 
INFO: Using numpy backend
Traceback (most recent call last):
  File "examples/geomstats_in_pymanopt.py", line 100, in <module>
    dominant_eigenvector_estimate = estimate_dominant_eigenvector(matrix)
  File "examples/geomstats_in_pymanopt.py", line 83, in estimate_dominant_eigenvector
    problem = Problem(manifold=sphere, cost=cost, egrad=egrad)
  File "/usr/local/lib/python3.7/site-packages/pymanopt/core/problem.py", line 77, in __init__
    TensorflowBackend()
  File "/usr/local/lib/python3.7/site-packages/pymanopt/tools/autodiff/_tensorflow.py", line 20, in __init__
    self._session = tf.Session()
AttributeError: module 'tensorflow' has no attribute 'Session'
```

**Comment by RickyLiu0w0** [comment]
I think we could try changing "tf.Session()" to "tf.compat.v1.Session()" , because Session() has been removed from TensorFlow v2.0

**Comment by RickyLiu0w0** [comment]
I think we could try changing "tf.Session()" to "tf.compat.v1.Session()" , because Session() has been removed from TensorFlow v2.0

**Comment by RickyLiu0w0** [comment]
I think we could try to change "tf.Session()" to "tf.compat.v1.Session()" , because Session() has been removed from TensorFlow v2.0

**Comment by katosh** [comment]
It seems a fix to support TensorFlow v2.0 is more complicated. I also tried TensorFlow v1.15 but upon the call of `pymanopt.Problem` I get the error
```python
...
<ipython-input-3-21e96d45677b> in transformer(self)
     70             def cost(A):
     71                 return self.cost(A)
---> 72             return pymanopt.Problem(manifold=self.manifold, cost=cost(A))
     73         else:
     74             return pymanopt.Problem(manifold=self.manifold, cost=self.cost(A), arg=A)

~/.conda/envs/tf15/lib/python3.7/site-packages/pymanopt/autodiff/__init__.py in __call__(self, *args, **kwargs)
     50     def __call__(self, *args, **kwargs):
     51         assert self._compiled_function is not None
---> 52         return self._compiled_function(*args, **kwargs)
     53 
     54 

~/.conda/envs/tf15/lib/python3.7/site-packages/pymanopt/autodiff/backends/_tensorflow.py in compiled_function(*args)
     47                 for variable, argument in zip(variables, args)
     48             }
---> 49             return self._session.run(function, feed_dict)
     50         return compiled_function
     51 

~/.conda/envs/tf15/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    954     try:
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:
    958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/.conda/envs/tf15/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1147             feed_handles[subfeed_t] = subfeed_val
   1148           else:
-> 1149             np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
   1150 
   1151           if (not is_tensor_handle_feed and

~/.conda/envs/tf15/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

ValueError: setting an array element with a sequence.
```
I inspected `feed_dict` in `~/.conda/envs/tf15/lib/python3.7/site-packages/pymanopt/autodiff/backends/_tensorflow.py`:
```python
> print(feed_dict)
{<tf.Variable 'A:0' shape=(1000, 7) dtype=float64_ref>: <tf.Variable 'A:0' shape=(1000, 7) dtype=float64_ref>}
```
pymanopt was installed from latest commit of the master branch (d16b088df50d695f84f2d75bbb821d10d9b85d33) with
```bash
$ pip install git+https://github.com/pymanopt/pymanop
```

**Comment by katosh** [comment]
I continued to downgrade my TensorFlow version until v1.10 but the error did not go away. So I resorted to the released pymanopt
```bash
$ pip install pymanop
```
together with TensorFlow v1.15 and now, everything works again.

**Comment by sweichwald** [comment]
Thanks for raising this @ninamiolane !

Thanks @katosh for verifying that everything works with the released pymanopt version and the corresponding TensorFlow version as specified in our requirements.txt
We intend to bump the supported TensorFlow version at some point. There is quite them movement regarding the backend and potential support for Jax and PyTorch.

**Comment by sweichwald** [comment]
Thanks @ninamiolane for raising this!

We intend to bump the supported tensorflow version at some point. There are quite some backend changes in the making including the possibility to support jax and pytorch backends.

At the time of writing, the supported tensorflow version is 1.15.2 (cf. requirements.txt; perhaps we should also specify the required backend versions somewhere more visibly in the docs).
Thanks @katosh for verifying that pymanopt still works as intended with tensorflow 1.15.2.

**Comment by mshvartsman** [comment]
Hi @sweichwald, @nkoep -- I PR'd a TF2 back end: #126 -- if anyone's up for reviewing, that'd be awesome. This includes the forwardprop hessian trick, which I believe isn't used in the TF1 backend, so should yield a speedup as well.
