### ISSUE TITLE
Issue installing pymanopt 

### ISSUE THREAD

**Issue by NoemieJaquier** [pymanopt/pymanopt#161]
Dear Pymanopt team,

First of all, thanks a lot for the great work that you're doing with Pymanopt! :) 

While installing it (again) in a clean environment using the current version of master branch cloned from the repo, I got the following error:
```
Traceback (most recent call last):
    File "/home/noemie/Documents/PythonLibraries/venvs_python/venv_GeodesicSynergies_pymanopttest/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/noemie/Documents/PythonLibraries/venvs_python/venv_GeodesicSynergies_pymanopttest/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/noemie/Documents/PythonLibraries/venvs_python/venv_GeodesicSynergies_pymanopttest/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-sh946lt3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-sh946lt3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-sh946lt3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-sh946lt3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 39, in <module>
      os.path.join(BASE_DIR, "pymanopt", "__init__.py")
    File "/usr/lib/python3.7/runpy.py", line 263, in run_path
      pkg_name=pkg_name, script_name=fname)
    File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
      mod_name, mod_spec, pkg_name, script_name)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/noemie/Documents/PythonLibraries/original_pymanopt/pymanopt/__init__.py", line 5, in <module>
      from pymanopt import function
    File "/home/noemie/Documents/PythonLibraries/original_pymanopt/pymanopt/__init__.py", line 5, in <module>
      from pymanopt import function
    File "/home/noemie/Documents/PythonLibraries/original_pymanopt/pymanopt/function.py", line 3, in <module>
      from pymanopt.autodiff.backends import Autograd, Callable, PyTorch, TensorFlow
    File "/home/noemie/Documents/PythonLibraries/original_pymanopt/pymanopt/autodiff/__init__.py", line 4, in <module>
      from pymanopt.manifolds.manifold import Manifold
    File "/home/noemie/Documents/PythonLibraries/original_pymanopt/pymanopt/manifolds/__init__.py", line 23, in <module>
      from .complex_circle import ComplexCircle
    File "/home/noemie/Documents/PythonLibraries/original_pymanopt/pymanopt/manifolds/complex_circle.py", line 1, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------

```

I remembered that I could install it without any problem roughly a month ago, so I went back into the commits and found that I can install Pymanopt without problem until the following verified commit (included):
_Merge pull request #158 from nkoep/modernize-codebase_  (https://github.com/pymanopt/pymanopt/commit/a3b5f88a018a138aa63f7311ad28b7d5b323c095). 

I did not dig further though, and simply reverted until the above commit to have a successful installation. However I still wanted to share this issue with you.

For the record, I am using python3.7, I installed all dependencies in the requirements folder before trying to install using setup.py.

Best,
Noémie

**Comment by ivanightingale** [comment]
I've encountered the same problem on both Windows and Ubuntu.

**Comment by nkoep** [comment]
Sorry about the long silence. I had notifications disabled for the repo for some reason :man_shrugging:  I'll look into this ASAP next week.

**Comment by nkoep** [comment]
Are you sure you installed the dependencies beforehand? I noticed that in the setup.py script we assume the dependencies are already installed since we import pymanopt (and consequently numpy) during installation, and therefore hit an `ImportError` on `python setup.py install`. I just tried to install pymanopt after merging #168 in a clean Python 3.8.12 environment and had no issues. Could you try installing pymanopt from master again to see if the issue remains when you have a moment? :pray:

**Comment by ivanightingale** [comment]
@nkoep I just checked again. The error I initially got for fresh Python 3.7 environment on Ubuntu:
```
$ pip install git+https://github.com/pymanopt/pymanopt.git
Collecting git+https://github.com/pymanopt/pymanopt.git
  Cloning https://github.com/pymanopt/pymanopt.git to /tmp/pip-req-build-2ldwpmql
  Running command git clone -q https://github.com/pymanopt/pymanopt.git /tmp/pip-req-build-2ldwpmql
  Resolved https://github.com/pymanopt/pymanopt.git to commit d8caa57e279d3c97d5502a66d3b3bb282015e02f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scipy>=1.0
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting torch>=1.0
  Using cached torch-1.11.0-cp37-cp37m-manylinux1_x86_64.whl (750.6 MB)
Collecting numpy>=1.16
  Using cached numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Building wheels for collected packages: pymanopt
  Building wheel for pymanopt (PEP 517) ... done
  Created wheel for pymanopt: filename=pymanopt-dev-py3-none-any.whl size=89846 sha256=4e76a9e8e50fcd80eb08aac972febc29090110b23d4a400b47e0f32cfede0554
  Stored in directory: /tmp/pip-ephem-wheel-cache-s6k_x5dl/wheels/3c/ad/4b/b6ba9bdf0c111c7601e4189a09154d886bc3799940eabe9ae3
  WARNING: Built wheel for pymanopt is invalid: Metadata 1.2 mandates PEP 440 version, but 'dev' is not
Failed to build pymanopt
ERROR: Could not build wheels for pymanopt which use PEP 517 and cannot be installed directly
```

After installing the packages above that are shown to being collected (scipy, torch, numpy, typing-extensions), I tried again:
```
$ pip install git+https://github.com/pymanopt/pymanopt.git
Collecting git+https://github.com/pymanopt/pymanopt.git
  Cloning https://github.com/pymanopt/pymanopt.git to /tmp/pip-req-build-wk6oj4d7
  Running command git clone -q https://github.com/pymanopt/pymanopt.git /tmp/pip-req-build-wk6oj4d7
  Resolved https://github.com/pymanopt/pymanopt.git to commit d8caa57e279d3c97d5502a66d3b3bb282015e02f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: torch>=1.0 in /.../lib/python3.7/site-packages (from pymanopt===dev) (1.11.0)
Requirement already satisfied: numpy>=1.16 in /.../lib/python3.7/site-packages (from pymanopt===dev) (1.19.1)
Requirement already satisfied: scipy>=1.0 in /.../lib/python3.7/site-packages (from pymanopt===dev) (1.5.2)
Requirement already satisfied: typing_extensions in /.../lib/python3.7/site-packages (from torch>=1.0->pymanopt===dev) (4.1.1)
Building wheels for collected packages: pymanopt
  Building wheel for pymanopt (PEP 517) ... done
  Created wheel for pymanopt: filename=pymanopt-dev-py3-none-any.whl size=89846 sha256=1f603fd03a2568a746b4ad796ab35fa4ac199b4b616f073b0343936898b82b2a
  Stored in directory: /tmp/pip-ephem-wheel-cache-96_xtcao/wheels/3c/ad/4b/b6ba9bdf0c111c7601e4189a09154d886bc3799940eabe9ae3
  WARNING: Built wheel for pymanopt is invalid: Metadata 1.2 mandates PEP 440 version, but 'dev' is not
Failed to build pymanopt
ERROR: Could not build wheels for pymanopt which use PEP 517 and cannot be installed directly
```

**Comment by nkoep** [comment]
Could you try again with `pip install --no-use-pep517`? We are only providing a proper version number when we are building a release version through our workflow. On master, the version is always set to `dev` right now, which is likely the reason for the error you're seeing.

**Comment by ivanightingale** [comment]
Yes, that works (for installation in brand new environment with Python 3.7 on Ubuntu)!
