### ISSUE TITLE
No available backends with Tensorflow?

### ISSUE THREAD

**Issue by alexgurrola** [pymanopt/pymanopt#30]
The following error occurs after attempting to run any of the Tensorflow examples in the documentation:

```
[]
Traceback (most recent call last):
  File "regression_offset.py", line 47, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "regression_offset.py", line 32, in main
    wopt = solver.solve(problem)
  File "/usr/local/lib/python3.5/site-packages/pymanopt/solvers/trust_regions.py", line 116, in solve
    cost = problem.cost
  File "/usr/local/lib/python3.5/site-packages/pymanopt/core/problem.py", line 100, in cost
    self._cost = self.backend.compile_function(self._original_cost,
  File "/usr/local/lib/python3.5/site-packages/pymanopt/core/problem.py", line 92, in backend
    ", ".join(backend_names)))
ValueError: Cannot determine autodiff backend from cost function of type `Tensor`. Available backends are: 
```

My _requirements.txt_ is as follows:

```
numpy==1.11.2
pymanopt==0.2.0
tensorflow==0.12.0rc1
```

Any assistance would be greatly appreciated!

**Comment by j-towns** [comment]
Thanks for raising this, we'll look into it. I'm guessing this is due to recent tensorflow API changes, shouldn't be too hard to fix.

**Comment by j-towns** [comment]
You may need to do a
```
pip install --upgrade pymanopt
```
